name: my_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-31.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# latest versions, run `flutter pub upgrade --major-versions`.
# newer versions, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/auth_repo
  user_repository:
    path: packages/user_repo
  http: ^0.13.4
  cupertino_icons: ^1.0.2

  google_fonts: ^4.0.3
  table_calendar: ^3.0.7
  provider: ^6.0.4
  flutter_dotenv: ^5.0.2
  restart_app: ^1.1.0+1
  mockito: ^5.3.2
  fluttertoast: ^8.1.2
  
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.2.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/makima.png
    - assets/Calendar.png
    - assets/ongoing_process.png
    - assets/start_new_process.png
    - assets/Bar Line.png
    - assets/images/google_image.png
    - assets/images/facebook_image.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
