name: flutter-ci

# Controls when the workflow will run

on:
  pull_request:                   # trigger: pull requests
    branches: [ main ]            # on branch main
    #- main                       # other way to do it

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  format: # check formatting issues in directory
    defaults:
      run:
        working-directory: my_app/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter format --set-exit-if-changed .
      - name: run echo
        run: echo check flutter format

  analyze: # check for errors in code
    defaults:
      run:
        working-directory: my_app/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter analyze
      - name: run echo
        run: echo check flutter analyze

  test:
    defaults:
      run:
        working-directory: my_app/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter test --coverage
      - run: sudo apt-get install lcov
      - run: lcov --summary coverage/lcov.info
      - name: run echo
        run: echo run tests coverage
  
  build-apk:
    defaults:
      run:
        working-directory: my_app/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    #    - uses: actions/setup-java@v1
    #    with:
 #       java-version: '12.x'
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
      - name: run echo
        run: echo build apk      
