name: flutter-ci

# Controls when the workflow will run

on:
  pull_request:                   # trigger: pull requests
    branches: [ preprod ]            # on branch preprod

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  check: # check formatting issues & anaylizing code for errors
    defaults:
      run:
        working-directory: my_app/workspace/ # setup work directory
    runs-on: ubuntu-latest # set the machine on which it will run
    steps:
      - uses: actions/checkout@v3 # check out of the repository so the workflow can access it | needs to be done for each job
      - uses: subosito/flutter-action@v2.3.0 # setup flutter environment for the workflow to run jobs on | also needs to be done for each new job
      - run: flutter format --set-exit-if-changed . 
      - run: flutter analyze
      - uses: EndBug/add-and-commit@v9

# add, commit & push if changes were made | WIP
# format code will probably setup a commit and push rule after formatting, might also mix format and analyze before pushing
      - name: run echo
        run: echo check flutter format and analyze for errors



  test: # running flutter tests
    defaults:
      run:
        working-directory: my_app/workspace/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter test --coverage
      - run: sudo apt-get install lcov
      - run: lcov --summary coverage/lcov.info
      - name: run echo
        run: echo run tests coverage
  
  build-apk: # build the app
    defaults:
      run:
        working-directory: my_app/workspace/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    #    - uses: actions/setup-java@v1
    #    with:
 #       java-version: '12.x'
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
      - name: run echo
        run: echo build apk      
